# Generated by Django 3.0.8 on 2020-07-14 14:48

from django.conf import settings
from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.custom_upload_to, verbose_name='Logo'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'user', 'address', 'city', 'country')},
        ),
    ]
