# Generated by Django 3.0.8 on 2020-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200714_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url_logo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Url Logo'),
        ),
    ]
