# Generated by Django 3.0.8 on 2020-07-14 14:48

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200714_1048'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='preparationcategory',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='preparationcategory',
            name='used',
            field=models.BooleanField(default=False, verbose_name='En uso'),
        ),
        migrations.AddField(
            model_name='preparationtype',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='preparationtype',
            name='used',
            field=models.BooleanField(default=False, verbose_name='En uso'),
        ),
        migrations.AlterField(
            model_name='preparations',
            name='category',
            field=models.ManyToManyField(related_name='get_category', to='menu.PreparationCategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='preparations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.custom_preparation_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='preparations',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='get_type', to='menu.PreparationType', verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('name', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='preparationcategory',
            unique_together={('name', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='preparationtype',
            unique_together={('name', 'restaurant')},
        ),
    ]
