# Generated by Django 3.0.8 on 2020-07-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_preparations_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparations',
            name='url_image',
        ),
    ]
