# Generated by Django 3.0.8 on 2020-07-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_preparations_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparations',
            name='url_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='url imagen'),
        ),
    ]
